import * as React from "react";
import { createFileRoute, useRouter } from "@tanstack/react-router";
import { Sparkles, ArrowRight, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { loginWithApi, verifyCodeWithApi } from "@/lib/auth-store";
import { toast } from "sonner";

export const Route = createFileRoute("/login")({ component: LoginPage });

function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [requireCode, setRequireCode] = React.useState(false);
  const [code, setCode] = React.useState("");
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState("");

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (requireCode) {
      if (!code.trim() || code.length !== 4) {
        setError("Enter the 4-digit verification code.");
        return;
      }
      setLoading(true);
      try {
        await verifyCodeWithApi(email, password, code);
        router.navigate({ to: "/" });
      } catch (err) {
        const message = (err as Error).message;
        setError(message);
        toast.error("Verification failed", { description: message });
      } finally {
        setLoading(false);
      }
      return;
    }

    if (!email.trim() || !password) {
      setError("Enter your email and password to sign in.");
      return;
    }
    setLoading(true);
    try {
      const res = await loginWithApi(email, password);
      if (res && "require_code" in res && res.require_code) {
        setRequireCode(true);
        toast.success("Verification required", {
          description: "A 4-digit code must be generated by the Super Admin to certify this login.",
        });
      } else {
        router.navigate({ to: "/" });
      }
    } catch (err) {
      const message = (err as Error).message;
      setError(message);
      toast.error("Sign-in failed", { description: message });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen grid place-items-center px-4">
      <div className="w-full max-w-md glass-strong rounded-3xl p-8 shadow-2xl">
        <div className="flex items-center gap-3 mb-8">
          <img
            src="/logo.png"
            className="h-11 rounded-xl shadow-md object-contain"
            alt="FAM Logo"
          />
          <div>
            <div className="text-lg font-semibold tracking-tight">Feedback Action Management</div>
            <div className="text-xs text-muted-foreground">Action Management Platform</div>
          </div>
        </div>

        <h1 className="text-2xl font-semibold tracking-tight">Welcome back</h1>
        <p className="text-sm text-muted-foreground mt-1 mb-6">Sign in to manage your reviews.</p>

        <form onSubmit={submit} noValidate className="space-y-4">
          {!requireCode ? (
            <>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  required
                  value={email}
                  onChange={(e) => {
                    setEmail(e.target.value);
                    setError("");
                  }}
                  className="bg-white/5 border-white/10"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  required
                  value={password}
                  onChange={(e) => {
                    setPassword(e.target.value);
                    setError("");
                  }}
                  className="bg-white/5 border-white/10"
                />
              </div>
            </>
          ) : (
            <div className="space-y-2">
              <Label htmlFor="code">Verification Code</Label>
              <Input
                id="code"
                type="text"
                maxLength={4}
                required
                placeholder="4-digit code"
                value={code}
                onChange={(e) => {
                  setCode(e.target.value.replace(/\D/g, ""));
                  setError("");
                }}
                className="bg-white/5 border-white/10 text-center text-2xl font-semibold tracking-widest uppercase font-mono h-12"
              />
              <p className="text-[11px] text-muted-foreground text-center mt-1">
                Enter the 4-digit code generated by the Super Admin in the cloud console.
              </p>
            </div>
          )}

          <Button type="submit" disabled={loading} className="w-full mt-2 group">
            {loading ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <>
                {requireCode ? "Verify Code" : "Sign in"}{" "}
                <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
              </>
            )}
          </Button>
          {error && (
            <p
              role="alert"
              className="rounded-lg border border-rose-400/25 bg-rose-400/10 px-3 py-2 text-xs text-rose-200"
            >
              Sign-in failed: {error}
            </p>
          )}
        </form>
      </div>
    </div>
  );
}
