/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResponsesRouteImport } from './routes/responses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesBuilderRouteImport } from './routes/templates.builder'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesRoute = ResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesBuilderRoute = TemplatesBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/responses': typeof ResponsesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/builder': typeof TemplatesBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/responses': typeof ResponsesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/builder': typeof TemplatesBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/responses': typeof ResponsesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/builder': typeof TemplatesBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/analytics'
    | '/devices'
    | '/login'
    | '/responses'
    | '/settings'
    | '/templates'
    | '/templates/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/analytics'
    | '/devices'
    | '/login'
    | '/responses'
    | '/settings'
    | '/templates'
    | '/templates/builder'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/analytics'
    | '/devices'
    | '/login'
    | '/responses'
    | '/settings'
    | '/templates'
    | '/templates/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DevicesRoute: typeof DevicesRoute
  LoginRoute: typeof LoginRoute
  ResponsesRoute: typeof ResponsesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses': {
      id: '/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof ResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/builder': {
      id: '/templates/builder'
      path: '/builder'
      fullPath: '/templates/builder'
      preLoaderRoute: typeof TemplatesBuilderRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesBuilderRoute: typeof TemplatesBuilderRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesBuilderRoute: TemplatesBuilderRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DevicesRoute: DevicesRoute,
  LoginRoute: LoginRoute,
  ResponsesRoute: ResponsesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
